name: Publish Docker Images
on:
  workflow_call:
    inputs:
      target-os:
        description: "List of operating systems to build on."
        default: '["ubuntu-latest"]'
        required: false
        type: string
      java-versions:
        description: "List of Java versions to target."
        default: '["21"]'
        required: false
        type: string

jobs:
  publish:
    name: Publish Docker Images
    strategy:
      matrix:
        os: ${{fromJson(inputs.target-os)}}
        java: ${{fromJson(inputs.java-versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Deploy (release only)
        run: sbt "buildClient; ci-release"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Log in to the Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images to registries
        run: sbt "buildClient; consensus / Docker / publish ; publicApi / Docker / publish"
        env:
          DOCKER_PUBLISH: true
          RELEASE_PUBLISH: true