name: Check and Deploy
on:
  workflow_call:

jobs:
  unit-tests:
    uses: ./.github/workflows/unit_tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration_tests.yml

  integration-monitor-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration_monitor_tests.yml