name: Unit Tests
on:
  workflow_call:

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.5
      - name: Check formatting
        run: sbt checkFormat
      - name: Run unit tests
        run: sbt coverage test
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: consensus/target/test-reports/