name: Integration Tests Monitor
on:
  workflow_call:
    inputs:
      target-os:
        description: "List of operating systems to build on."
        default: '["ubuntu-latest"]'
        required: false
        type: string
      java-versions:
        description: "List of Java versions to target."
        default: '["11"]'
        required: false
        type: string

jobs:
  integration-tests-monitor:
    name: Integration Tests Monitor
    strategy:
      matrix:
        os: ${{fromJson(inputs.target-os)}}
        java: ${{fromJson(inputs.java-versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker version
        uses: docker://docker
        with:
          args: docker -v
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Run integration tests Monitor
        run: |
          docker run -d --rm --add-host host.docker.internal:host-gateway -p 18444:18444 -p 18443:18443 -p 28332:28332 --name=bitcoind ruimarinho/bitcoin-core -chain=regtest -zmqpubrawblock=tcp://0.0.0.0:28332 -rpcuser=test -rpcpassword=test -port=18444 -rpcport=18443 -rpcbind=:18443 -rpcallowip=0.0.0.0/0
          docker run -d --rm --name bitcoind2 --add-host host.docker.internal:host-gateway -p 12224:18444 -p 12223:18443 -p 12222:28332 ruimarinho/bitcoin-core -chain=regtest -zmqpubrawblock=tcp://0.0.0.0:28332 -rpcuser=