name: Pull Request

on:
  pull_request:
    branches:
    - "*"

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit_tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/_integration_tests.yml

  integration-monitor-tests:
    needs: unit-tests
    uses: ./.github/workflows/_integration_monitor_tests.yml
