name: Push Main

on:
  push:
    branches:
    - "*"
    tags: ["*"]

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit_tests.yml

  integration-tests:
    needs: [unit-tests]
    uses: ./.github/workflows/_integration_tests.yml

  integration-monitor-tests:
    needs: [unit-tests]
    uses: ./.github/workflows/_integration_monitor_tests.yml

  publish:
    name: Publish Docker Images
    needs: [unit-tests, integration-tests, integration-monitor-tests]
    uses: ./.github/workflows/_publish_docker_images.yml
    secrets: inherit

   
  # deploy-docs:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   needs: [ sbt-build-and-test ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: npm
  #         cache-dependency-path: microsite/package-lock.json
  #     - name: Install dependencies
  #       run: cd microsite && npm ci
  #     - name: Build website
  #       run: cd microsite &&  npm run build
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./microsite/build
  #         user_name: github-actions[bot]
  #         user_email: 41898282+github-actions[bot]@users.noreply.github.com
