name: Push Main

on:
  push:
    branches:
    - "*"
    tags: ["*"]

jobs:
  sbt-build-and-test:
    uses: ./.github/workflows/_sbt_build_and_test.yml
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: sbt-build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "21"
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Deploy (release only)
      run: sbt "buildClient; ci-release"
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Log in to the Github Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push images to registries
      run: sbt "buildClient; consensus / Docker / publish ; publicApi / Docker / publish"
      env:
        DOCKER_PUBLISH: true
        RELEASE_PUBLISH: true
  # deploy-docs:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   needs: [ sbt-build-and-test ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: npm
  #         cache-dependency-path: microsite/package-lock.json
  #     - name: Install dependencies
  #       run: cd microsite && npm ci
  #     - name: Build website
  #       run: cd microsite &&  npm run build
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./microsite/build
  #         user_name: github-actions[bot]
  #         user_email: 41898282+github-actions[bot]@users.noreply.github.com
