name: Unit Tests
on:
  workflow_call:
    inputs:
      target-os:
        description: "List of operating systems to build on."
        default: '["ubuntu-latest"]'
        required: false
        type: string
      java-versions:
        description: "List of Java versions to target."
        default: '["11"]'
        required: false
        type: string

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt checkFormat
      - name: Run unit tests
        run: sbt coverage test
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: consensus/target/test-reports/